//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTecUtil.Cultures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTecUtil.Cultures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled by user.
        /// </summary>
        public static string Comms_Cancelled {
            get {
                return ResourceManager.GetString("Comms_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled by user.
        /// </summary>
        public static string Comms_Cancelled_By_User {
            get {
                return ResourceManager.GetString("Comms_Cancelled_By_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected - read-only.
        /// </summary>
        public static string Comms_Connected_ReadOnly {
            get {
                return ResourceManager.GetString("Comms_Connected_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected for read/write.
        /// </summary>
        public static string Comms_Connected_Writeable {
            get {
                return ResourceManager.GetString("Comms_Connected_Writeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Comms_Direction_Download {
            get {
                return ResourceManager.GetString("Comms_Direction_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string Comms_Direction_Idle {
            get {
                return ResourceManager.GetString("Comms_Direction_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Comms_Direction_Upload {
            get {
                return ResourceManager.GetString("Comms_Direction_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Comms_Disconnected {
            get {
                return ResourceManager.GetString("Comms_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete..
        /// </summary>
        public static string Comms_Download_Complete {
            get {
                return ResourceManager.GetString("Comms_Download_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download was not completed..
        /// </summary>
        public static string Comms_Download_Incomplete {
            get {
                return ResourceManager.GetString("Comms_Download_Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The panel&apos;s firmware version is not supported by this Programming Tool..
        /// </summary>
        public static string Comms_Firmware_Not_Supported {
            get {
                return ResourceManager.GetString("Comms_Firmware_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening for logging data.
        /// </summary>
        public static string Comms_Listening {
            get {
                return ResourceManager.GetString("Comms_Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** End **.
        /// </summary>
        public static string Comms_Log_End {
            get {
                return ResourceManager.GetString("Comms_Log_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Comms_Request {
            get {
                return ResourceManager.GetString("Comms_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Comms_Send {
            get {
                return ResourceManager.GetString("Comms_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete..
        /// </summary>
        public static string Comms_Upload_Complete {
            get {
                return ResourceManager.GetString("Comms_Upload_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upload was not completed..
        /// </summary>
        public static string Comms_Upload_Incomplete {
            get {
                return ResourceManager.GetString("Comms_Upload_Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: download complete..
        /// </summary>
        public static string Comms_x_Download_Complete {
            get {
                return ResourceManager.GetString("Comms_x_Download_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: upload complete..
        /// </summary>
        public static string Comms_x_Upload_Complete {
            get {
                return ResourceManager.GetString("Comms_x_Upload_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Start.
        /// </summary>
        public static string Download_Start {
            get {
                return ResourceManager.GetString("Download_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data was received from the panel..
        /// </summary>
        public static string Error_Checksum_Fail {
            get {
                return ResourceManager.GetString("Error_Checksum_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The panel is not responding..
        /// </summary>
        public static string Error_Download_Retries {
            get {
                return ResourceManager.GetString("Error_Download_Retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed because the panel did not respond within the time limit..
        /// </summary>
        public static string Error_Download_Timeout {
            get {
                return ResourceManager.GetString("Error_Download_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while receiving data from the panel..
        /// </summary>
        public static string Error_Downloading_Data {
            get {
                return ResourceManager.GetString("Error_Downloading_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while generating report: &apos;{0}&apos;.
        /// </summary>
        public static string Error_Generating_Report_x {
            get {
                return ResourceManager.GetString("Error_Generating_Report_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview is not available.
        ///The previewer delegate has not been set..
        /// </summary>
        public static string Error_Print_Previewer_NotSet {
            get {
                return ResourceManager.GetString("Error_Print_Previewer_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing Error.
        /// </summary>
        public static string Error_Printing {
            get {
                return ResourceManager.GetString("Error_Printing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while printing the document..
        /// </summary>
        public static string Error_Printing_Document {
            get {
                return ResourceManager.GetString("Error_Printing_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range is invalid..
        /// </summary>
        public static string Error_Range_Invalid {
            get {
                return ResourceManager.GetString("Error_Range_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more items not valid for this equation has been removed.
        /// </summary>
        public static string Error_Range_Invalid_Item {
            get {
                return ResourceManager.GetString("Error_Range_Invalid_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range values could not be interpreted.
        /// </summary>
        public static string Error_Range_Parse_Error {
            get {
                return ResourceManager.GetString("Error_Range_Parse_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many items.
        /// </summary>
        public static string Error_Range_Too_Many_Items {
            get {
                return ResourceManager.GetString("Error_Range_Too_Many_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many items (max {0}).
        /// </summary>
        public static string Error_Range_Too_Many_Items_Max_x {
            get {
                return ResourceManager.GetString("Error_Range_Too_Many_Items_Max_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item was outside the allowed values.
        /// </summary>
        public static string Error_Range_Value_Out_Of_Range {
            get {
                return ResourceManager.GetString("Error_Range_Value_Out_Of_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading comms log.
        /// </summary>
        public static string Error_Reading_Comms_Log {
            get {
                return ResourceManager.GetString("Error_Reading_Comms_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening the serial port..
        /// </summary>
        public static string Error_Serial_Port {
            get {
                return ResourceManager.GetString("Error_Serial_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload cancelled because the panel is not responding..
        /// </summary>
        public static string Error_Upload_Retries {
            get {
                return ResourceManager.GetString("Error_Upload_Retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed because the panel did not respond within the time limit..
        /// </summary>
        public static string Error_Upload_Timeout {
            get {
                return ResourceManager.GetString("Error_Upload_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending data to the panel..
        /// </summary>
        public static string Error_Uploading_Data {
            get {
                return ResourceManager.GetString("Error_Uploading_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string File_Save_As {
            get {
                return ResourceManager.GetString("File_Save_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mins.
        /// </summary>
        public static string Minutes_Short {
            get {
                return ResourceManager.GetString("Minutes_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string No_Data {
            get {
                return ResourceManager.GetString("No_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        public static string Not_Set {
            get {
                return ResourceManager.GetString("Not_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Option_Cancel {
            get {
                return ResourceManager.GetString("Option_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Option_No {
            get {
                return ResourceManager.GetString("Option_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Option_Ok {
            get {
                return ResourceManager.GetString("Option_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Option_Yes {
            get {
                return ResourceManager.GetString("Option_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pages.
        /// </summary>
        public static string Print_All_Pages {
            get {
                return ResourceManager.GetString("Print_All_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All panels.
        /// </summary>
        public static string Print_All_Panels {
            get {
                return ResourceManager.GetString("Print_All_Panels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current page.
        /// </summary>
        public static string Print_Current_Page {
            get {
                return ResourceManager.GetString("Print_Current_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current panel.
        /// </summary>
        public static string Print_Current_Panel {
            get {
                return ResourceManager.GetString("Print_Current_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** system name not set **.
        /// </summary>
        public static string Print_Error_System_Name_Not_Set {
            get {
                return ResourceManager.GetString("Print_Error_System_Name_Not_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies:.
        /// </summary>
        public static string Print_Num_Copies {
            get {
                return ResourceManager.GetString("Print_Num_Copies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by:.
        /// </summary>
        public static string Print_Order_By {
            get {
                return ResourceManager.GetString("Print_Order_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        public static string Print_Page_x_Of_y {
            get {
                return ResourceManager.GetString("Print_Page_x_Of_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panels:.
        /// </summary>
        public static string Print_Panels {
            get {
                return ResourceManager.GetString("Print_Panels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview Error.
        /// </summary>
        public static string Print_Preview_Error {
            get {
                return ResourceManager.GetString("Print_Preview_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select pages:.
        /// </summary>
        public static string Print_Select_Pages {
            get {
                return ResourceManager.GetString("Print_Select_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer not found.
        /// </summary>
        public static string Printer_Not_Found {
            get {
                return ResourceManager.GetString("Printer_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        public static string PrintQueueStatus_Busy {
            get {
                return ResourceManager.GetString("PrintQueueStatus_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door open.
        /// </summary>
        public static string PrintQueueStatus_DoorOpen {
            get {
                return ResourceManager.GetString("PrintQueueStatus_DoorOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string PrintQueueStatus_Error {
            get {
                return ResourceManager.GetString("PrintQueueStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialising.
        /// </summary>
        public static string PrintQueueStatus_Initialising {
            get {
                return ResourceManager.GetString("PrintQueueStatus_Initialising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving data.
        /// </summary>
        public static string PrintQueueStatus_IOActive {
            get {
                return ResourceManager.GetString("PrintQueueStatus_IOActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for manual feed.
        /// </summary>
        public static string PrintQueueStatus_ManualFeed {
            get {
                return ResourceManager.GetString("PrintQueueStatus_ManualFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is not specified.
        /// </summary>
        public static string PrintQueueStatus_None {
            get {
                return ResourceManager.GetString("PrintQueueStatus_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status information is unavailable.
        /// </summary>
        public static string PrintQueueStatus_NotAvailable {
            get {
                return ResourceManager.GetString("PrintQueueStatus_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of toner.
        /// </summary>
        public static string PrintQueueStatus_NoToner {
            get {
                return ResourceManager.GetString("PrintQueueStatus_NoToner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string PrintQueueStatus_Offline {
            get {
                return ResourceManager.GetString("PrintQueueStatus_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of memory.
        /// </summary>
        public static string PrintQueueStatus_OutOfMemory {
            get {
                return ResourceManager.GetString("PrintQueueStatus_OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output bin is full.
        /// </summary>
        public static string PrintQueueStatus_OutputBinFull {
            get {
                return ResourceManager.GetString("PrintQueueStatus_OutputBinFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to print current page.
        /// </summary>
        public static string PrintQueueStatus_PagePunt {
            get {
                return ResourceManager.GetString("PrintQueueStatus_PagePunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper jam.
        /// </summary>
        public static string PrintQueueStatus_PaperJam {
            get {
                return ResourceManager.GetString("PrintQueueStatus_PaperJam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of paper.
        /// </summary>
        public static string PrintQueueStatus_PaperOut {
            get {
                return ResourceManager.GetString("PrintQueueStatus_PaperOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper problem.
        /// </summary>
        public static string PrintQueueStatus_PaperProblem {
            get {
                return ResourceManager.GetString("PrintQueueStatus_PaperProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print queue paused.
        /// </summary>
        public static string PrintQueueStatus_Paused {
            get {
                return ResourceManager.GetString("PrintQueueStatus_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting print job.
        /// </summary>
        public static string PrintQueueStatus_PendingDeletion {
            get {
                return ResourceManager.GetString("PrintQueueStatus_PendingDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power save mode.
        /// </summary>
        public static string PrintQueueStatus_PowerSave {
            get {
                return ResourceManager.GetString("PrintQueueStatus_PowerSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing.
        /// </summary>
        public static string PrintQueueStatus_Printing {
            get {
                return ResourceManager.GetString("PrintQueueStatus_Printing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string PrintQueueStatus_Processing {
            get {
                return ResourceManager.GetString("PrintQueueStatus_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string PrintQueueStatus_Ready {
            get {
                return ResourceManager.GetString("PrintQueueStatus_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string PrintQueueStatus_ServerUnknown {
            get {
                return ResourceManager.GetString("PrintQueueStatus_ServerUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toner low.
        /// </summary>
        public static string PrintQueueStatus_TonerLow {
            get {
                return ResourceManager.GetString("PrintQueueStatus_TonerLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: requires user action.
        /// </summary>
        public static string PrintQueueStatus_UserIntervention {
            get {
                return ResourceManager.GetString("PrintQueueStatus_UserIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for print job.
        /// </summary>
        public static string PrintQueueStatus_Waiting {
            get {
                return ResourceManager.GetString("PrintQueueStatus_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warming up.
        /// </summary>
        public static string PrintQueueStatus_WarmingUp {
            get {
                return ResourceManager.GetString("PrintQueueStatus_WarmingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ←.
        /// </summary>
        public static string Receive_Abbr {
            get {
                return ResourceManager.GetString("Receive_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Print Options.
        /// </summary>
        public static string Select_Print_Options {
            get {
                return ResourceManager.GetString("Select_Print_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer:.
        /// </summary>
        public static string Select_Printer {
            get {
                return ResourceManager.GetString("Select_Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to →.
        /// </summary>
        public static string Send_Abbr {
            get {
                return ResourceManager.GetString("Send_Abbr", resourceCulture);
            }
        }
    }
}
